// planImport tests — the "re-import does not duplicate" checkpoint.
//   node test/import-plan.test.mjs
//
// planImport is pure, so the database is stood in for by the same two lookups
// db.existingForImport() builds: byKey (import_key) and byFront (front_norm).

import { readFileSync } from 'node:fs';
import { parse, planImport, cardToRow, frontNormOf } from '../js/importer.js';

const R = new URL('../', import.meta.url);
const read = (p) => readFileSync(new URL(p, R), 'utf8');

let failed = 0;
const check = (label, cond, extra = '') => {
  if (!cond) failed++;
  console.log(`${cond ? 'pass' : 'FAIL'}  ${label}${extra ? '   ' + extra : ''}`);
};
const eq = (label, got, want) => check(label, JSON.stringify(got) === JSON.stringify(want),
  JSON.stringify(got) === JSON.stringify(want) ? '' : `got ${JSON.stringify(got)} want ${JSON.stringify(want)}`);

const SUBJECT = 'sub-1';
const UNIT = 'unit-1';
const empty = () => ({ rows: [], byKey: new Map(), byFront: new Map() });

/**
 * Stand-in for the database: turn a set of just-imported rows into the same
 * lookups existingForImport() returns, the way Postgres would after an insert.
 */
function asStored(rows) {
  const stored = rows.map((r, i) => ({
    id: `card-${i}`,
    import_key: r.import_key,
    // front_norm is generated by Postgres from the content column.
    front_norm: frontNormOf(r.content),
    content: r.content,
    unit_id: r.unit_id,
    ivl: 12, ease: 2.35, due: '2026-10-01', reps: 9, lapses: 1,
  }));
  const byKey = new Map();
  const byFront = new Map();
  for (const s of stored) {
    if (s.import_key) byKey.set(s.import_key, s);
    if (s.front_norm) byFront.set(s.front_norm, s);
  }
  return { rows: stored, byKey, byFront };
}

const u1 = parse(read('data/thermo-unit1.json'));
const u2 = parse(read('data/thermo-unit2.txt'));

// ── first import into an empty subject ──────────────────────────────────────
console.log('\n── first import (empty subject) ───────────────────────────');

const first1 = planImport(u1.cards, empty());
eq('thermo-unit1.json: 36 new, 0 duplicate, 0 update',
  [first1.counts.new, first1.counts.duplicate, first1.counts.update], [36, 0, 0]);

const first2 = planImport(u2.cards, empty());
eq('thermo-unit2.txt: 7 new, 0 duplicate, 0 update',
  [first2.counts.new, first2.counts.duplicate, first2.counts.update], [7, 0, 0]);
eq('reverse requests counted but not turned into cards', first2.counts.reverse, 1);

// ── the checkpoint: re-import the same file ─────────────────────────────────
console.log('\n── re-import the same file ────────────────────────────────');

const rows1 = first1.rows.map((r) => cardToRow(r.card, SUBJECT, UNIT));
const stored1 = asStored(rows1);
const again1 = planImport(u1.cards, stored1);

// Every card in thermo-unit1.json carries an id, so they match on import_key
// and land as schedule-preserving updates rather than new rows.
eq('thermo-unit1.json re-import: 0 new',
  again1.counts.new, 0);
eq('thermo-unit1.json re-import: 36 matched, not 36 new',
  again1.counts.duplicate + again1.counts.update, 36);
console.log(`   matched as: ${again1.counts.update} update (by id), ${again1.counts.duplicate} duplicate (by front)`);

const rows2 = first2.rows.map((r) => cardToRow(r.card, SUBJECT, UNIT));
const again2 = planImport(u2.cards, asStored(rows2));
// The text format has no `id`, so these match on front_norm instead.
eq('thermo-unit2.txt re-import: 0 new', again2.counts.new, 0);
eq('thermo-unit2.txt re-import: 7 duplicates (no ids, matched on front_norm)',
  again2.counts.duplicate, 7);

// ── id wins over front text ─────────────────────────────────────────────────
console.log('\n── matching order: id first, then front_norm ──────────────');

const oneCard = parse(JSON.stringify({
  cards: [{ id: 'k-1', type: 'qa', content: { front: 'Define entropy.', back: 'old' } }],
}));
const storedOne = asStored([cardToRow(oneCard.cards[0], SUBJECT, UNIT)]);

// Same id, changed front: still an update, because id is checked first.
const edited = parse(JSON.stringify({
  cards: [{ id: 'k-1', type: 'qa', content: { front: 'Define entropy precisely.', back: 'new' } }],
}));
const editPlan = planImport(edited.cards, storedOne);
eq('same id + changed front = update', editPlan.counts.update, 1);
eq('…and it points at the stored row', editPlan.rows[0].existing.id, 'card-0');

// No id, same front: duplicate.
const noId = parse(JSON.stringify({
  cards: [{ type: 'qa', content: { front: 'Define entropy.', back: 'other' } }],
}));
eq('no id + same front = duplicate', planImport(noId.cards, storedOne).counts.duplicate, 1);

// Front differing only in case and punctuation is still the same front.
const punct = parse(JSON.stringify({
  cards: [{ type: 'qa', content: { front: '  DEFINE   ENTROPY!!  ', back: 'x' } }],
}));
eq('front_norm ignores case, spacing and punctuation',
  planImport(punct.cards, storedOne).counts.duplicate, 1);

// ── a payload that repeats itself ───────────────────────────────────────────
console.log('\n── self-duplicates inside one payload ─────────────────────');
const selfDupe = parse(JSON.stringify({
  cards: [
    { type: 'qa', content: { front: 'Same front', back: 'a' } },
    { type: 'qa', content: { front: 'same  front.', back: 'b' } },
    { type: 'qa', content: { front: 'Different', back: 'c' } },
  ],
}));
const sd = planImport(selfDupe.cards, empty());
eq('the second copy inside one payload is a duplicate',
  [sd.counts.new, sd.counts.duplicate], [2, 1]);

// ── cardToRow shape ─────────────────────────────────────────────────────────
console.log('\n── row shape ──────────────────────────────────────────────');
const row = cardToRow(u1.cards[0], SUBJECT, UNIT);
eq('row keys match the remento_cards columns we write', Object.keys(row).sort(), [
  'content', 'figure_ref', 'import_key', 'importance', 'marks', 'note',
  'source', 'subject_id', 'tags', 'trap', 'type', 'unit_id', 'why',
]);
check('row carries no schedule columns — those are the database defaults',
  !('ivl' in row) && !('due' in row) && !('ease' in row) && !('reps' in row));
eq('unit_id is null when importing at subject level',
  cardToRow(u1.cards[0], SUBJECT, null).unit_id, null);
eq('import_key comes from the payload id', row.import_key, 'thermo-u1-001');

console.log(`\n${failed === 0 ? 'ALL PASS' : failed + ' FAILED'}  —  planImport\n`);
process.exit(failed ? 1 : 0);
